In [1]:
import pandas as pd

pd.set_option("display.max_columns", None)

## Setup

In [2]:
# setup your dataset path
dataset_local_path = "/tmp/"
y, m, d = "2024", "03", "01"

## AFC

In [3]:
afc = pd.read_parquet(f"{dataset_local_path}afc-{y}-{m}-{d}.parquet")
afc.head()

,cod_card,afc_datetime,integration,route_short_name,direction_id,value,vehicle
0,card_87788adcc649,2024-03-01 18:44:52,True,MT02,NaN,4.1,59393
1,card_6e7fdb73af1d,2024-03-01 12:49:48,True,MT02,NaN,4.1,58447
2,card_8fd9be492bf7,2024-03-01 19:22:07,True,MT02,NaN,4.1,45188
3,card_a3979b39ea3d,2024-03-01 15:17:49,True,MT02,NaN,4.1,58384
4,card_d14ee2131a1d,2024-03-01 10:10:27,True,MT02,NaN,4.1,58797

## AVL

### AVL-lines

In [4]:
avl_lines = pd.read_parquet(f"{dataset_local_path}avl-lines-{y}-{m}-{d}.parquet")
avl_lines.head()

,route_short_name,pt_sequence,direction_id,longitude,latitude,stop_id,route_long_name,service_code
0,0116,1,I,-38.511230,-12.983389,43768720,"Avenida Vale Do Tororo 327, Salvador - Bahia, ...",53786
1,0116,2,I,-38.511097,-12.986428,45832898,"Avenida Vale do Tororó, 291 - Nazaré, Salvador...",53786
2,0116,3,I,-38.511448,-12.990091,44782328,"Praça Dr. João Mangabeira, 627-679 - Garcia, S...",53786
3,0116,4,I,-38.504387,-12.990533,44784448,"Av. Vaco da Gama, S/N - Federação, Salvador - ...",53786
4,0116,5,I,-38.501972,-12.992005,44784449,"Av. Vasco da Gama, 271 - Federação, Salvador -...",53786

### AVL-vehicles

In [5]:
avl_veic = pd.read_parquet(f"{dataset_local_path}avl-vehicles-{y}-{m}-{d}.parquet")
avl_veic.head()

,vehicle,route_short_name,direction_id,gps_datetime,longitude,latitude,stop_id,service_code
0,20001,0310,I,2024-03-01 05:53:20,-38.512428,-12.978642,45834426,45546
1,20001,0310,I,2024-03-01 05:53:53,-38.509964,-12.975935,45834425,45546
2,20001,0310,I,2024-03-01 05:53:57,-38.509964,-12.975935,45834425,45546
3,20001,0310,I,2024-03-01 05:54:02,-38.508957,-12.975689,44782954,45546
4,20001,0310,I,2024-03-01 05:54:47,-38.508957,-12.975689,44782954,45546

### AVL full

In [6]:
# stop by stop in vehicle running
avl = avl_veic.merge(avl_lines, 
                     on=["route_short_name", "direction_id", "stop_id", "service_code", "longitude", "latitude"], 
                     how="left")

In [7]:
avl.head()

,vehicle,route_short_name,direction_id,gps_datetime,longitude,latitude,stop_id,service_code,pt_sequence,route_long_name
0,20001,0310,I,2024-03-01 05:53:20,-38.512428,-12.978642,45834426,45546,1.0,"Ladeira Das Hortas 93, Salvador - Bahia, 40040..."
1,20001,0310,I,2024-03-01 05:53:53,-38.509964,-12.975935,45834425,45546,NaN,NaN
2,20001,0310,I,2024-03-01 05:53:57,-38.509964,-12.975935,45834425,45546,NaN,NaN
3,20001,0310,I,2024-03-01 05:54:02,-38.508957,-12.975689,44782954,45546,2.0,"Avenida José Joaquim Seabra, 107-123 - Nazaré,..."
4,20001,0310,I,2024-03-01 05:54:47,-38.508957,-12.975689,44782954,45546,2.0,"Avenida José Joaquim Seabra, 107-123 - Nazaré,..."

## General Transit Feed Specification (GTFS)

### GTFS Agency

In [8]:
agency = pd.read_csv(f"{dataset_local_path}agency.txt")
agency.head()

,agency_id,agency_name,agency_url,agency_timezone,agency_lang,agency_phone
0,1,company_i,http://www.cittati.com.br,America/Sao_Paulo,pt,NaN
1,2,company_ii,http://www.cittati.com.br,America/Sao_Paulo,pt,NaN

### GTFS Routes

In [9]:
routes = pd.read_csv(f"{dataset_local_path}routes.txt")
routes.head()

,route_id,agency_id,route_short_name,route_long_name,route_desc,route_type,route_color,route_text_color
0,4089,1,1230,Sussuarana x Barra R1.,NaN,3,NaN,NaN
1,4450,1,1321,São Marcos x Barroquinha,NaN,3,NaN,NaN
2,4518,1,1103,Alto do Cruzeiro/Pernambués x Shop.Bela Vista/...,NaN,3,NaN,NaN
3,4523,1,1405,Estação Pirajá x Cajazeiras 8,NaN,3,NaN,NaN
4,4524,1,1137,Pernambués x Barra,NaN,3,NaN,NaN

### GTFS Trips

In [10]:
trips = pd.read_csv(f"{dataset_local_path}trips.txt")
trips.head()

,route_id,service_id,trip_id,trip_headsign,direction_id,block_id,shape_id
0,4089,26082_D_1046761,1046761_D_1_0,*SUSSUARANA X BARRA R1 VIA COMÉRCIO/C.GRANDE,0,4089_001M,26082_I
1,4089,26082_D_1046761,1046761_D_1_1,*BARRA R1 X SUSSUARANA VIA GARIBALDI/ITAIGARA,1,4089_001M,26082_V
2,4089,26082_D_1046761,1046761_D_2_0,*SUSSUARANA X BARRA R1 VIA COMÉRCIO/C.GRANDE,0,4089_002M,26082_I
3,4089,26082_D_1046761,1046761_D_2_1,*BARRA R1 X SUSSUARANA VIA GARIBALDI/ITAIGARA,1,4089_002M,26082_V
4,4089,26082_D_1046761,1046761_D_3_0,*SUSSUARANA X BARRA R1 VIA COMÉRCIO/C.GRANDE,0,4089_002T,26082_I

### GTFS Stops Times

In [11]:
stop_times = pd.read_csv(f"{dataset_local_path}stop_times.txt")
stop_times.head()

,trip_id,arrival_time,departure_time,stop_id,stop_sequence,stop_headsign,pickup_type,drop_off_type
0,1046761_D_1_0,08:30:00,08:30:00,43968810,1,NaN,0,0
1,1046761_D_1_0,08:31:41,08:31:41,47566106,2,NaN,0,0
2,1046761_D_1_0,08:33:49,08:33:49,44782337,3,NaN,0,0
3,1046761_D_1_0,08:34:55,08:34:55,44784470,4,NaN,0,0
4,1046761_D_1_0,08:35:44,08:35:44,44784471,5,NaN,0,0

### GTFS Stops

In [12]:
stops_df = pd.read_csv(f"{dataset_local_path}stops.txt")
stops_df.head()

,stop_id,stop_name,stop_desc,stop_lat,stop_lon,zone_id,stop_url,location_type,parent_station
0,43968810_S,R. São Cristóvão 2 - Sussuarana Salvador - BA ...,SUSSUARANA VELHA,-12.931565,-38.444393,NaN,NaN,1,NaN
1,43968810,R. São Cristóvão 2 - Sussuarana Salvador - BA ...,SUSSUARANA VELHA,-12.931565,-38.444393,NaN,NaN,0,43968810_S
2,47566106_S,Av. Ulysses Guimarães 4067 - Sussuarana Salvad...,NaN,-12.933859,-38.446774,NaN,NaN,1,NaN
3,47566106,Av. Ulysses Guimarães 4067 - Sussuarana Salvad...,NaN,-12.933859,-38.446774,NaN,NaN,0,47566106_S
4,44782337,Av. Ulysses Guimarães 4314-4322 - Novo Horizon...,NaN,-12.935150,-38.440578,NaN,NaN,0,NaN

## Local Trip Information (LTI)

In [13]:
lti = pd.read_parquet(f"{dataset_local_path}lti-2024-03-01.parquet")
lti.head()

,route_short_name,service_code,direction_id,vehicle,start_trip,end_trip,activity
0,T014,74335,I,20401,01/03/2024 17:03:49,01/03/2024 17:10:45,Saída de Garagem
1,T014,74335,I,20516,01/03/2024 05:37:16,01/03/2024 05:40:36,Saída de Garagem
2,T014,74335,I,20516,01/03/2024 17:11:40,01/03/2024 17:20:58,Saída de Garagem
3,T014,74335,I,20086,01/03/2024 05:39:27,01/03/2024 05:46:38,Saída de Garagem
4,T014,74335,I,20401,01/03/2024 12:37:47,01/03/2024 12:42:04,Recolhe

## Boarding

In [14]:
boarding = pd.read_parquet(f"{dataset_local_path}boarding-{y}-{m}-{d}.parquet")
boarding.head()

,tripuserid,type_bus,user_type,set,registers,trip_id,start_trip,end_trip,tolerance,integration,cod_card,stop_time,register_time,service_code,linha_afc,route_short_name,vehicle_afc,vehicle,stop_id,order,direction_id,trip,dif_boarding,viagem,classification,motive,trip_sequence,set_nb,stop_time_nb,hora_pe,route_short_name_nb,vehicle_nb,stop_id_nb,diff_nb,motive_pe,target_boarding
0,02310030998400_20240301114921,metro,deficiente,metro,1,metro,2024-03-01 11:49:21,2024-03-01 11:49:21,NaT,False,card_e9d5dafe4b96,2024-03-01 11:49:21,2024-03-01 11:49:21,NaN,MT02,MT02,59831,59831,BTS,1.0,metro,1.0,0.0,dentro,regular,single_trip,single_trip,NaN,NaT,NaT,NaN,NaN,NaN,NaN,single trip,irregular
1,02310031021456_20240301053615,metro,deficiente,metro,2,metro,2024-03-01 05:36:15,2024-03-01 05:36:15,NaT,False,card_2c2ebacfcb43,2024-03-01 05:36:15,2024-03-01 05:36:15,NaN,MT02,MT02,59353,59353,JUA,1.0,metro,1.0,0.0,dentro,regular,regular,firt_trip,metro,2024-03-01 14:26:15,2024-03-01 14:26:15,MT02,59527,PNB,0.0,regular,regular
2,02310031021456_20240301142615,metro,deficiente,metro,2,metro,2024-03-01 14:26:15,2024-03-01 14:26:15,NaT,False,card_2c2ebacfcb43,2024-03-01 14:26:15,2024-03-01 14:26:15,NaN,MT02,MT02,59527,59527,PNB,1.0,metro,1.0,0.0,dentro,regular,regular,last_trip,metro,NaT,2024-03-02 05:36:15,MT02,59353,JUA,0.0,regular,regular
3,02310031023008_20240301061138,metro,deficiente,metro,2,metro,2024-03-01 06:11:38,2024-03-01 06:11:38,NaT,False,card_42ffc6c52946,2024-03-01 06:11:38,2024-03-01 06:11:38,NaN,MT02,MT02,58296,58296,ARP,1.0,metro,1.0,0.0,dentro,regular,regular,firt_trip,metro,2024-03-01 17:04:21,2024-03-01 17:04:21,MT02,58449,LPA,0.0,regular,regular
4,02310031023008_20240301170421,metro,deficiente,metro,2,metro,2024-03-01 17:04:21,2024-03-01 17:04:21,NaT,False,card_42ffc6c52946,2024-03-01 17:04:21,2024-03-01 17:04:21,NaN,MT02,MT02,58449,58449,LPA,1.0,metro,1.0,0.0,dentro,regular,regular,last_trip,metro,NaT,2024-03-02 06:11:38,MT02,58296,ARP,0.0,regular,regular

## Alighting

In [15]:
alighting = pd.read_parquet(f"{dataset_local_path}alighting-{y}-{m}-{d}.parquet")
alighting.head()

,tripuserid,stop_time_ali,stop_id_ali,order_ali,walk_target,trip_ali,walk_dis,walk_time,walk_speed,diff_de_pe,wait_time,trip_dis,trip_time,vel_media,bridge,bridge_type,bridge_id,chain,target_ws,target_avs,target_tt,target_td,target_alighting
0,02310031021456_20240301053615,NaT,PNB,NaN,ok,NaN,0.0,0.000000,5.0,NaN,NaN,4.12,NaN,NaN,False,sem_ponte,NaN,metro-metro,ok,fora_parametro,irregular,ok,ok
1,02310031021456_20240301142615,NaT,JUA,NaN,ok,NaN,0.0,0.000000,5.0,NaN,NaN,4.12,NaN,NaN,False,sem_ponte,NaN,metro-metro,ok,fora_parametro,irregular,ok,ok
2,02310031023008_20240301061138,NaT,LPA,NaN,ok,NaN,0.0,0.000000,5.0,NaN,NaN,20.48,NaN,NaN,False,sem_ponte,NaN,metro-metro,ok,fora_parametro,irregular,ok,ok
3,02310031023008_20240301170421,NaT,ARP,NaN,ok,NaN,0.0,0.000000,5.0,NaN,NaN,20.48,NaN,NaN,False,sem_ponte,NaN,metro-metro,ok,fora_parametro,irregular,ok,ok
4,02310031024892_20240301153935,NaT,CAB,NaN,excessiva,NaN,1.4,16.799999,5.0,NaN,NaN,1.40,NaN,NaN,False,sem_ponte,NaN,metro-metro,ok,fora_parametro,irregular,ok,walk_distance_irregular

## OD

In [16]:
od = pd.read_parquet(f"{dataset_local_path}od-{y}-{m}-{d}.parquet")
od.head()

,route_short_name,register_code,direction_id,pt_sequence,stop_id,vehicle,trip_number,trip_id,start_trip,end_trip,stop_time,n-boardings,n-alighting,lag_loading,balance,loading
0,1141,12730,I,1,44028970,21201,1,21201_1141_1,2024-03-01 06:07:50,2024-03-01 07:19:33,2024-03-01 06:07:50,8.918203,0.0,0.000000,0.000000,8.918203
1,1141,12730,I,2,44783401,21201,1,21201_1141_1,2024-03-01 06:07:50,2024-03-01 07:19:33,2024-03-01 06:07:52,5.573877,0.0,8.918203,8.918203,14.492080
2,1141,12730,I,3,44783402,21201,1,21201_1141_1,2024-03-01 06:07:50,2024-03-01 07:19:33,2024-03-01 06:08:49,5.573877,0.0,14.492080,14.492080,20.065956
3,1141,12730,I,4,45833865,21201,1,21201_1141_1,2024-03-01 06:07:50,2024-03-01 07:19:33,2024-03-01 06:10:12,6.688653,0.0,20.065956,20.065956,26.754610
4,1141,12730,I,5,44739642,21201,1,21201_1141_1,2024-03-01 06:07:50,2024-03-01 07:19:33,2024-03-01 06:11:26,6.688653,0.0,26.754610,26.754610,33.443260